const CARD_DEFS = {
  red_bull: {
    id: 'red_bull',
    name: 'Red Bull',
    emoji: '🐂',
    system: 'player_stat',
    target: 'self',
    description: 'Power +2, Nerve -1',
    flavorText: '给你翅膀',
    effect: { powerMod: 2, nerveMod: -1 },
  },
  drunk_swing: {
    id: 'drunk_swing',
    name: 'Drunk Swing',
    emoji: '🍺',
    system: 'player_stat',
    target: 'self',
    description: 'Power random +/-3',
    flavorText: '闭眼，挥',
    effect: { powerRandom: 3, weirdCommentary: true },
  },
  zen_mode: {
    id: 'zen_mode',
    name: 'Zen Mode',
    emoji: '🧘',
    system: 'player_stat',
    target: 'self',
    description: 'Nerve +2, Power -1',
    flavorText: '稳住，别浪',
    effect: { nerveMod: 2, powerMod: -1 },
  },
  hot_head: {
    id: 'hot_head',
    name: 'Hot Head',
    emoji: '😤',
    system: 'player_stat',
    target: 'self',
    description: 'Power +1, Aim +1, Curse +30%',
    flavorText: '越怒越猛',
    effect: { powerMod: 1, aimMod: 1, curseTriggerBonus: 30 },
  },

  // ─── Player stat cards (3 more) ───
  iron_grip: {
    id: 'iron_grip',
    name: 'Iron Grip',
    emoji: '🦾',
    system: 'player_stat',
    deck: 'base',
    target: 'self',
    description: 'Aim +3, Nerve -2',
    flavorText: 'Iron-wrist swing.',
    effect: { aimMod: 3, nerveMod: -2 },
  },
  power_nap: {
    id: 'power_nap',
    name: 'Power Nap',
    emoji: '😴',
    system: 'player_stat',
    deck: 'base',
    target: 'self',
    description: 'Nerve +1, Power +1, Aim -1',
    flavorText: 'Slept like a baby. Back in business.',
    effect: { nerveMod: 1, powerMod: 1, aimMod: -1 },
  },
  blind_faith: {
    id: 'blind_faith',
    name: 'Blind Faith',
    emoji: '🙈',
    system: 'player_stat',
    deck: 'base',
    target: 'self',
    description: 'Power +4, Aim -3',
    flavorText: 'Hit hard, hope for the best.',
    effect: { powerMod: 4, aimMod: -3 },
  },

  // ─── Weather cards (5) ───
  left_wind: {
    id: 'left_wind',
    name: 'Left Wind',
    emoji: '💨',
    system: 'weather',
    deck: 'base',
    target: 'all',
    description: 'All balls shift left 5-15yd',
    flavorText: "Blowin' in the wind.",
    effect: { offsetXRange: [-15, -5] },
  },
  right_wind: {
    id: 'right_wind',
    name: 'Right Wind',
    emoji: '🌬️',
    system: 'weather',
    deck: 'base',
    target: 'all',
    description: 'All balls shift right 5-15yd',
    flavorText: "Wind's doing its thing.",
    effect: { offsetXRange: [5, 15] },
  },
  rain: {
    id: 'rain',
    name: 'Rain',
    emoji: '🌧️',
    system: 'weather',
    deck: 'base',
    target: 'all',
    description: 'Push distance -30%',
    flavorText: "Can't hit far in the rain.",
    effect: { pushMultiplier: 0.7 },
  },
  tailwind: {
    id: 'tailwind',
    name: 'Tailwind',
    emoji: '🏃',
    system: 'weather',
    deck: 'base',
    target: 'all',
    description: 'Push distance +20%',
    flavorText: 'Perfect breeze. Charge!',
    effect: { pushMultiplier: 1.2 },
  },
  fog: {
    id: 'fog',
    name: 'Fog',
    emoji: '🌫️',
    system: 'weather',
    deck: 'base',
    target: 'all',
    description: 'All balls random offset 3-8yd',
    flavorText: "Can't see a thing out here.",
    effect: { offsetXRange: [-8, 8] },
  },

  // ─── Animal event cards (5) ───
  squirrel_tax: {
    id: 'squirrel_tax',
    name: 'Squirrel Tax',
    emoji: '🐿️',
    system: 'animal_event',
    deck: 'base',
    target: 'opponent',
    description: 'Opponent ball displaced 5-20yd',
    flavorText: 'That squirrel took your ball.',
    effect: { displacementRange: [5, 20], displacementAxis: 'both' },
  },
  mole_tunnel: {
    id: 'mole_tunnel',
    name: 'Mole Tunnel',
    emoji: '🕳️',
    system: 'animal_event',
    deck: 'base',
    target: 'self',
    description: 'Ball jumps forward 10-30yd',
    flavorText: "Mole bro's got your back.",
    effect: { displacementRange: [10, 30], displacementAxis: 'forward' },
  },
  angry_goose: {
    id: 'angry_goose',
    name: 'Angry Goose',
    emoji: '🦆',
    system: 'animal_event',
    deck: 'base',
    target: 'opponent',
    description: 'Opponent next shot Nerve -2',
    flavorText: 'The goose is watching you.',
    effect: { nerveMod: -2 },
  },
  sly_fox: {
    id: 'sly_fox',
    name: 'Sly Fox',
    emoji: '🦊',
    system: 'animal_event',
    deck: 'base',
    target: 'opponent',
    description: 'Opponent next shot Aim -2',
    flavorText: 'Fox stole your sense of direction.',
    effect: { aimMod: -2 },
  },
  lucky_rabbit: {
    id: 'lucky_rabbit',
    name: 'Lucky Rabbit',
    emoji: '🐰',
    system: 'animal_event',
    deck: 'base',
    target: 'self',
    description: 'Ball jumps forward 5-15yd',
    flavorText: 'The rabbit knows a shortcut.',
    effect: { displacementRange: [5, 15], displacementAxis: 'forward' },
  },
}

export const STAT_CARD_POOL = Object.keys(CARD_DEFS)

// ─── Brainrot Deck (10 cards) ───

const BRAINROT_DEFS = {
  // ─── Drinks (3) ───
  br_red_bull_ultra: {
    id: 'br_red_bull_ultra',
    name: 'Red Bull Ultra™',
    emoji: '⚡',
    system: 'player_stat',
    deck: 'brainrot',
    target: 'self',
    description: 'Power +6 (can exceed 10, max 15)',
    flavorText: 'Gives you wings. Direction not included. FDA not consulted.',
    effect: { powerMod: 6, allowOverflow: true, overflowCap: 15 },
  },
  br_mystery_flask: {
    id: 'br_mystery_flask',
    name: 'Mystery Flask',
    emoji: '🧪',
    system: 'player_stat',
    deck: 'brainrot',
    target: 'self',
    description: 'Power/Aim/Touch each random 1-12',
    flavorText: 'Could be steroids. Could be tap water. Roll the dice.',
    effect: { randomizeAll: true, randomRange: [1, 12] },
  },
  br_scope_creep: {
    id: 'br_scope_creep',
    name: 'Scope Creep',
    emoji: '🔭',
    system: 'player_stat',
    deck: 'brainrot',
    target: 'self',
    description: 'Aim = 12 (laser), Power = 2 (short)',
    flavorText: 'We want everything. We get 40 yards.',
    effect: { aimOverride: 12, powerOverride: 2 },
  },

  // ─── Creatures (2) ───
  br_dragon: {
    id: 'br_dragon',
    name: "Dragon's Hoard",
    emoji: '🐉',
    system: 'animal_event',
    deck: 'brainrot',
    target: 'opponent',
    description: "Opponent ball stolen 30-70yd",
    flavorText: "The dragon doesn't have opinions. It has a catapult.",
    effect: { displacementRange: [30, 70], displacementAxis: 'both' },
  },
  br_void_fish: {
    id: 'br_void_fish',
    name: 'Void Fish',
    emoji: '🐟',
    system: 'animal_event',
    deck: 'brainrot',
    target: 'opponent',
    description: 'Opponent ball teleported 3-25yd from hole',
    flavorText: 'The void fish operates on vibes and chaos.',
    effect: { teleportNearHole: true, teleportRange: [3, 25] },
  },

  // ─── Weather (2) ───
  br_gravity: {
    id: 'br_gravity',
    name: 'Gravity Anomaly',
    emoji: '🌍',
    system: 'weather',
    deck: 'brainrot',
    target: 'all',
    description: 'Distance x1.8',
    flavorText: "Gravity called in sick today. No one's driving.",
    effect: { pushMultiplier: 1.8 },
  },
  br_wildfire: {
    id: 'br_wildfire',
    name: 'Wildfire',
    emoji: '🔥',
    system: 'weather',
    deck: 'brainrot',
    target: 'all',
    description: 'All balls random offset 15-30yd',
    flavorText: 'The course is on fire. The balls are fleeing.',
    effect: { offsetXRange: [-30, 30] },
  },

  // ─── Pure Brainrot (3) ───
  br_ball_swap: {
    id: 'br_ball_swap',
    name: 'Ball Swap',
    emoji: '🔄',
    system: 'animal_event',
    deck: 'brainrot',
    target: 'both',
    description: 'Swap your ball position with opponent',
    flavorText: 'Yours is mine. No takebacks.',
    effect: { swapPositions: true },
  },
  br_identity_theft: {
    id: 'br_identity_theft',
    name: 'Identity Theft',
    emoji: '🎭',
    system: 'player_stat',
    deck: 'brainrot',
    target: 'self',
    description: 'Use opponent Power/Aim/Touch this shot',
    flavorText: "I'm you but better. Deal with it.",
    effect: { copyOpponentStats: true },
  },
  br_nuclear_option: {
    id: 'br_nuclear_option',
    name: 'Nuclear Option',
    emoji: '☢️',
    system: 'brainrot_meta',
    deck: 'brainrot',
    target: 'all',
    description: 'Reset hole: all balls to tee, strokes to 0',
    flavorText: "Mutually assured destruction. But make it golf.",
    effect: { resetHole: true },
  },
}

export const BRAINROT_CARD_POOL = Object.keys(BRAINROT_DEFS)

export function getPool(deckType) {
  return deckType === 'brainrot' ? BRAINROT_CARD_POOL : STAT_CARD_POOL
}

export function dealCard(pool) {
  return pool[Math.floor(Math.random() * pool.length)]
}

export function getCardDef(id) {
  return CARD_DEFS[id] || BRAINROT_DEFS[id] || null
}

export default CARD_DEFS
